import useAxios from "axios-hooks";
import type { NextPage } from "next";
import Head from "next/head";
import { MovieOverviewList } from "../types/Movie";
import { getHeaders } from "../utils/getCredentials";

interface Props {
  headers: { Authorization: string };
}

const Home: NextPage<Props> = ({ headers }) => {
  const [{ data, loading, error }, refetch] = useAxios<MovieOverviewList>({
    url: "https://api.themoviedb.org/4/discover/movie",
    headers,
  });

  const movies = data?.results || [];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
    </>
  );
};

export const getStaticProps = async () => ({
  props: {
    headers: getHeaders(),
  },
});

export default Home;
