import { Heading } from "@chakra-ui/layout";
import type { NextPage } from "next";
import Head from "next/head";
import { MovieSlider } from "../components/MovieSlider";
import { useMovieOverviews } from "../hooks/useOverviews";

interface Props {}

const Home: NextPage<Props> = () => {
  const { movies: discover } = useMovieOverviews("discover");
  const { movies: trending } = useMovieOverviews("trending");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Discover</Heading>
      <MovieSlider movies={discover} />
      <Heading>Tending</Heading>
      <MovieSlider movies={trending} />
    </>
  );
};

export default Home;
